# Site settings
title: MoGee
email: morten@moge.dk
url: https://mogee.dk
description: "Apps til alle og enhver!"
keywords: "apps"
tagline: "Apps til alle og enhver!"
meta_author: Morten Bjerg Gregersen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

social:
  - title: twitter
    url: http://twitter.com/MortenGregersen
  - title: facebook
    url: https://www.facebook.com/MoGee.dk
  - title: linkedin
    url: https://www.linkedin.com/in/mortengregersen
  - title: github
    url: http://github.com/MortenGregersen
  - title: stack-overflow
    url: https://stackoverflow.com/users/687540/morten-bjerg-gregersen

# Build settings
markdown: kramdown